---
output: html_document
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  echo = FALSE
)
```

We'd like to thank the tremendous effort of our team who have contributed to this project (twitter handles): Gautam Dey (@Dey_Gautam), Srivats Venkataramanan (@srivatsv), Sundar Naganathan (@Sundar_Ram_07), Debbie Ho, Zhang-He Goh (@zhanghe_goh), Kirsty Hooper (@KirstyHooper13), Lars Hubatsch (@LarsHubatsch), Mariana De Niz (@mariana_deniz), Sejal Davla (@JustABrainThing), Mate Palfy (@mate_palfy) & Jonny Coates (@JACoates91). 

We would also like to thanks the contributors from the eLife Sprint 2020 and those who continue to help develop this site: Michael Parkin, Hugo Gruson, Chris Huggins, Bruno Paranhos & Allan Ochola.  

The database is being actively maintiained & managed by Zhang-He Goh (@zhanghe_goh), Gautam Dey (@Dey_Gautam) & Jonny Coates (@JACoates91). For any queries or questions please contact Jonny at jonathon.coates@qmul.ac.uk or preLights at prelights@biologists.com

In addition, our thanks go out to the wider scientific community who are diligently assessing and communicating important preprints during this difficult time. 

Please note that by including content on this site, we do not endorse or claim to verify the preprint contents nor can we independently confirm the results. It is with the best effort that we collate and review the included preprints but cannot be held liable for any inaccuracies. 


                                 
        
