---
output: html_document
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  echo = FALSE,
  message = FALSE,
  warning = FALSE
)
```

<link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;600&family=PT+Serif:ital,wght@0,400;0,700;1,400&display=swap" rel="stylesheet">

```{css}
* {
  box-sizing: border-box;
}

body {
  background-color: white;
  font-family: 'Open Sans', sans-serif;
}

/* We do not have a table of content so we can use the full width instead of 75% */
.col-md-9 {
  width: 100%;
}

a {
  color: #0079C3;
    text-decoration: none;
  
}

a:hover {
  text-decoration: underline;
}

span {
  font-size:	14px;
  margin: 0;
  margin-bottom:6px;
}

p {
  
  font-family: 'PT Serif', serif;
  font-size:14px;
  color: #767676;
    margin:0;
  margin-right:24px;
  
}

h1 {
  font-size:48px;
  margin: 12px 0;
}


h2 {
  font-size:16px;
  margin: 0 12px 6px 0;
  
}

.timeline h2 {
  padding-top: 0;
  margin-top: 0;
}


.right h2 {
  
  margin-right: 0px;
  margin-left: 12px;
  font-size: 14px;
  font-weight:400;
  color:#212121;
    
}

/* The actual timeline (the vertical ruler) */
.timeline {
  display:block;
  position: relative;
  max-width: 1200px;
  margin: 120px auto;
  
}

/* The actual timeline (the vertical ruler) */
.timeline::after {
  content: '';
  position: absolute;
  width: 2px;
  background-color: grey;
  top: 0;
  bottom: 0;
  left: 75%;
  
}

/* Container around content */
.container_tl {
  position: relative;
  background-color: inherit;
  /* display: grid;
  grid-template-columns: auto auto; */
  display: flex;
  flex-direction: column;
  margin-bottom:24px
  
}

/* Place the container to the left */
.left {
  left: 0;
}

/* Place the container to the right */
.right {
  left: 75%;
}


/* The actual content */
.content {
  position: relative;
  display: flex;
  
}

.connector {
  /* grid-column: 2 / span 1; */
  /* width: 100%; */
  border-bottom: 1px solid grey;
  height: 14px;
  min-width: 100px;
  flex-grow: 1;
  
}

.container_tl.left {
  
  width: 75%;
  
}

/* The circles on the timeline */
.left .connector::after {
  content: '';
  position: absolute;
  width: 10px;
  height: 10px;
  right: -6px;
  background-color: grey;
  top: 8px;
  border-radius: 50%;
  z-index: 1;
}


/* The circles on the timeline */
.right .connector::before {
  content: '';
  position: absolute;
  width: 10px;
  height: 10px;
  left: -4px;
  background-color: grey;
  top: 8px;
  border-radius: 50%;
  z-index: 1;
}

.container_tl.right {
  width: 25%;
}

.container_tl.right .connector {
  
  width: 100px;
  flex-grow: 0;
  
}

/* styling for the month markers on the timeline */
.month-marker {
  display:inline-block;
  position: relative;
  z-index:1000;
  left:75%;
  margin-left:-35px;
  background-color:#212121;
    color:white;
  height:24px;
  border-radius:2px;
  margin-bottom:24px;
}

.month-marker span {
  margin:4px 8px;
}


/* position and style the date markers */
span.date {
  align-self: flex-end;
  font-size:12px;
  color:#767676;
    margin:0 12px -6px;
}

/* move the dates on key events to the left */
.right span.date {
  align-self:flex-start;
}

/* Media queries - Responsive timeline on screens less than 730px wide */
  @media screen and (max-width: 730px) {
    
    /* hide the timeline */
    .timeline::after {
      display:none
    }
    
    /* Full-width containers */
    .container_tl.left {
      width: 100%;
      padding:12px;
      left: 0;
    }
  
    /*hide the connectors */
    .connector {
      display: none;
      
    }
    
    /* hide the dots */
    .connector::before, .connector::after {
      display: none;
    }
  
    
    .container_tl.right {
      
      padding:12px;
      text-align: right;
      width: 75%;
      left: 20%;
    }
    
    .container_tl.right h2 {
      width: 100%;
    }
    
    .content {
      width: 100%;
    }
    
  }
```

```{r, load_libraries}
library(tidyverse)  # general data wrangling
library(lubridate)  # handling dates
library(googlesheets4)  # importing Google Sheets
library(europepmc)  # retrieving preprint metadata
library(rAltmetric)  # retrieving Altmetric scores
library(httr) 
```

```{r, setup_google_sheets}
# Set Google de-authentication mode as sheet is public
# N.B. Authentication will be required if sheet is made private
googlesheets4::gs4_deauth()

# Set Google Sheet URL
sheet_url <- "https://docs.google.com/spreadsheets/d/1BES52D4nYUZjV6kx1S_lJKSHvC9I0uzPTFA2mcxv4FI"
```

```{r, define_utilities}
parse_epmc <- function(item){
  data <- item[[1]]
  if(length(data[["commentCorrectionList"]]) > 0){
    l <- data[["commentCorrectionList"]][["commentCorrection"]]
    for(i in l){
      if(i[["type"]] == "Preprint of"){
        pub_doi <- epmc_details(i[["id"]], i[["source"]])[["basic"]][["doi"]]
      }
      if (is.null(pub_doi)) {
        pub_doi <- NA_character_
      }
    }
  } else {
    pub_doi <- NA_character_
  }
  prelights_link <- epmc_lablinks(ext_id = data$id, data_src = data$source,
                                  lab_id = "1859", verbose = FALSE) %>%
    { map_chr(.$link, "url") }
  if(is_empty(prelights_link)) prelights_link <- NA_character_
  return(tibble(title = data[["title"]],
                date = as_date(data[["firstPublicationDate"]]),
                authorString = str_c(str_split(data[["authorString"]],
                                               ", ")[[1]][[1]], " et al."),
                publishedVersionDoi = pub_doi,
                citationCount = data[["citedByCount"]],
                preLightsUrl = prelights_link))
}

# Function to return Altmetric info for a DOI
altmetric <- function(doi){
  data <- altmetrics(doi = doi) %>%
    altmetric_data()
  return(tibble(altmetricScore = ceiling(as.integer(data$score)),
                tweeters = data$cited_by_tweeters_count,
                altmetricDonut = data$images.small,
                altmetricUrl = data$details_url))
}
```


```{r, fetch_metadata}
# Read Google Sheet (Preprints tab) and add data
preprints <- read_sheet(sheet_url, sheet = "Preprints") %>%
  filter(class %in% c("preprint", "bad")) %>% # filter non-preprints
  filter(!str_detect(id, "arXiv")) %>% # filter arXiv preprints (for now...)
  mutate(publication = map(epmc_search_by_doi(id, output = "raw"), parse_epmc),
         altmetric = map(id, altmetric),
         url = str_c("https://doi.org/", id)) %>%
  unnest(publication) %>%
  unnest(altmetric)

# Read Google Sheet (Events tab)
events <- read_sheet(sheet_url, sheet = "Events") %>%
  filter(class %in% c("event"))

# Combine and write to JSON object
combined <- bind_rows(preprints, events) %>%
  select(date, class, title, url,
         briefSummary, longerSummary,
         authorString, publishedVersionDoi, citationCount,
         altmetricScore, altmetricUrl, altmetricDonut, tweeters,
         preLightsUrl
  ) %>%
  arrange(date) %>%
  as.data.frame()
```

# Covid Preprints

## A timeline of landmark preprints in response to COVID-19.

```{r, results='asis'}
cat('<div class="timeline">')

month <- "init"

for (i in seq_len(nrow(combined))) {
  
  new_month <- format(combined[i, "date"], "%b %Y")
  
  if (new_month != month) {
    cat('<div class="month-marker">')
    cat('<span>', new_month, '</span>')
    cat('</div>')
    month <- new_month
  }
  
  if (combined[i, "class"] %in% c("preprint", "bad")) {
    cat('<div class="container_tl left">')
    cat('<span class="date">', sprintf("%sth", format(combined[i, "date"], "%e")), '</span>')
    cat('<div class="content">')
    cat('<h2><a href=', combined[i, "url"], '>', combined[i, "title"], '</a></h2>')
    cat('<div class="connector"></div>')
    cat('</div>')
    cat('<span class="author-name">', combined[i, "authorString"], '</span>')
    cat('<p>', combined[i, "briefSummary"], '</p>')
    cat('</div>')
  } else if (combined[i, "class"] == "event") {
    cat('<div class="container_tl right">')
    cat('<span class="date">', sprintf("%sth", format(combined[i, "date"], "%e")), '</span>')
    cat('<div class="content">')
    cat('<div class="connector"></div>')
    cat('<h2><a href=', combined[i, "url"], '>', combined[i, "title"], '</a></h2>')
    cat('</div>')
    cat('</div>')
  }

}

cat('</div>')
```
