on:
  schedule:
    - cron:  '0 5 * * 1'

name: Render-dashboard

jobs:
  dashboarddown:
    name: Render-dashboard
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
      - uses: r-lib/actions/setup-r@v1
      - uses: r-lib/actions/setup-pandoc@v1
      - name: Install dependencies
        run: |
          install.packages('remotes')
          saveRDS(remotes::install_packages(c("httr", "dplyr")), ".github/depends.Rds", version = 2)
          writeLines(sprintf("R-%i.%i", getRversion()$major, getRversion()$minor), ".github/R-version")
        shell: Rscript {0}
      - name: Cache R packages
        uses: actions/cache@v1
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-${{ hashFiles('.github/depends.Rds') }}
          restore-keys: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-
      - name: Run code to update plot
        run: |
          Rscript update_plot.R
      - name: git config
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "gh-actions committer"
      - name: Commit results
        run: |
          git add .
          git commit -m 'Update preprint data'
          git push https://${{github.actor}}:${{secrets.GITHUB_TOKEN}}@github.com/${{github.repository}}.git
